---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
  description: The title of the project
  config:
    required: true
- type: text
  name: subtitle
  label: Subtitle
  description: The text shown just below the project title.
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: file
  name: thumb_img_path
  label: Featured Image
  description: The image shown in the project page.
- type: file
  name: content_img_path
  label: Alternative Featured Image
  description: The image shown in the single project.
- type: text
  name: template
  label: Template
  hidden: true
  default: project
  config:
    required: true
